name: Deploy Backend

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: SSH into EC2 and deploy
        uses: appleboy/ssh-action@master
        with:
          host: 54.252.217.169
          username: ubuntu
          key: ${{ secrets.EC2_SECRETKEY }}
          script: |
            cd ~/PatientManagementSystem
            git pull origin main
            sudo docker-compose down
            sudo docker-compose up -d --build
            cd frontend/app
            NODE_OPTIONS="--max-old-space-size=2048" npm run build
            pm2 start serve --name "patient-frontend" -- -s build -l 3000
